routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('wmssearch', 'WifiController@wmssearch')->name('wmssearch');

Route::middleware('auth')->name('dashboard.')->namespace('Dashboard')->group(function () {
    
    // Main Menu 👌
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('home', 'HomeController@index');
    // Route::get('exist', [App\Http\Controllers\ExistController::class, 'index'])->name('exist');
    
    // Patient 🚧
    Route::prefix('exist')->name('exist')->namespace('Exist')->group(function () {
        // page view 👌
        Route::get('/', 'ExistController@index');
        Route::get('profil/{id}', 'ExistController@show')->name('.profile');
        Route::get('existsearch', 'ExistController@existsearch')->name('.existsearch');
    });

    Route::prefix('roadmap')->name('roadmap')->namespace('Roadmap')->group(function () {
        // page view 👌
        Route::get('/', 'RoadmapController@index');
        Route::get('profil/{id}', 'ExistController@show')->name('.profile');
    });

    Route::prefix('laporan')->name('laporan')->namespace('Laporan')->group(function () {
        // page view 👌
        Route::get('/', 'LaporanController@index');
    });

    Route::prefix('manajemen')->name('manajemen')->namespace('Manajemen')->group(function () {
        // page view 👌
        Route::get('/', 'ManajemenController@index');
    });
    
    Route::prefix('pengaturan')->name('pengaturan')->namespace('Pengaturan')->group(function () {
        // page view 👌
        Route::get('/', 'PengaturanController@index');
        Route::get('sales', 'PengaturanController@sales')->name('.sales');
        Route::post('salesstore', 'PengaturanController@salesstore')->name('.salesstore');
        Route::post('salesupdate/{id}', 'PengaturanController@salesupdate')->name('.salesupdate');
        Route::get('salesdelete/{id}', 'PengaturanController@salesdelete')->name('.salesdelete');
        Route::get('salesdetail/{id}', 'PengaturanController@show')->name('.salesdetail');

        Route::get('paket', 'PaketController@index')->name('.paket');
        Route::post('paketstore', 'PaketController@store')->name('.paketstore');
        Route::post('paketupdate/{id}', 'PaketController@update')->name('.paketupdate');
        Route::get('paketdelete/{id}', 'PaketController@destroy')->name('.paketdelete');
        Route::get('paketedit/{id}', 'PaketController@edit')->name('.paketedit');
    });

    Route::prefix('registrasi')->name('registrasi')->namespace('Registrasi')->group(function () {
        // page view 👌
        Route::get('/', 'WifiController@index');
        Route::get('prospek', 'WifiController@prospek')->name('.prospek');

        Route::get('prospekedit/{id}', 'WifiController@edit')->name('.prospekedit');
        Route::post('prospekupdate/{id}', 'WifiController@prospekupdate')->name('.prospekupdate');
        Route::get('profil/{id}', 'WifiController@show')->name('.profile');
        Route::get('wmscreate', 'WifiController@create')->name('.wmscreate');

        Route::get('wmsedit/{id}', 'WifiController@editwms')->name('.wmsedit');
        Route::get('wms', 'WifiController@wms')->name('.wms');
        Route::post('wmsupdate/{id}', 'WifiController@updatewms')->name('.wmsupdate');
        Route::post('wmsupdatephoto/{id}', 'WifiController@updatewmsphoto')->name('.wmsupdatephoto');
        Route::get('wmsdelete/{id}', 'WifiController@destroywms')->name('.wmsdelete');
        Route::get('wmssearch', 'WifiController@wmssearch')->name('.wmssearch');

        
        Route::post('store', 'WifiController@store')->name('.store');
        Route::post('prospekstore', 'WifiController@prospekstore')->name('.prospekstore');
        Route::post('wmsstore', 'WifiController@store2')->name('.wmsstore');

    });


});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row">
                <div class="col-xl-6 col-md-6 col-12 mb-4">
                <a href="{{ route('dashboard.registrasi')  }}" class="dashboard card shadow" style="border-radius: 1rem;">
                        <div class="card-header bg-purple-old-fade py-2" style="
                        background-color: red;
                        border-radius: 1rem 1rem 0rem 0rem;">
                            <h5 class="text-white mb-0">
                                Registrasi Baru
                            </h5>
                        </div>
                        <div class="card-body">
                            {{-- Amount --}}
                            <div class="media">
                                <h1 class="mr-2 d-flex">
                                    <i class="fa fa-1x fa fa-file-text-o px-4 py-4 m-auto text-dark"></i>
                                </h1>
                                <div class="media-body my-auto">
                                    <h2 class="my-0 text-secondary">Registrasi</h2>
                                    <hr class="mt-0 mb-2">
                                    {{-- <h5 class="text-dark mb-0">
                                         Pasien
                                    </h5> --}}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-xl-6 col-md-6 col-12 mb-4">
                    <a href="{{ route('dashboard.exist')  }}" class="dashboard card shadow" style="border-radius: 1rem;">
                        <div class="card-header bg-purple-old-fade py-2" style="
                        background-color: red;
                        border-radius: 1rem 1rem 0rem 0rem;">
                            <h5 class="text-white mb-0">
                                Data Pelanggan
                            </h5>
                        </div>
                        <div class="card-body">
                            {{-- Amount --}}
                            <div class="media">
                                <h1 class="mr-2 d-flex">
                                    <i class="fa fa-1x fa-users px-4 py-4 m-auto text-dark"></i>
                                </h1>
                                <div class="media-body my-auto">
                                    <h2 class="my-0 text-secondary">Data Existing</h2>
                                    <hr class="mt-0 mb-2">
                                    {{-- <h5 class="text-dark mb-0">
                                         Pasien
                                    </h5> --}}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-xl-6 col-md-6 col-12 mb-4">
                    <a href="{{ route('dashboard.laporan')  }}" class="dashboard card shadow" style="border-radius: 1rem;">
                        <div class="card-header bg-purple-old-fade py-2" style="
                        background-color: red;
                        border-radius: 1rem 1rem 0rem 0rem;">
                            <h5 class="text-white mb-0">
                                Laporan
                            </h5>
                        </div>
                        <div class="card-body">
                            {{-- Amount --}}
                            <div class="media">
                                <h1 class="mr-2 d-flex">
                                    <i class="fa fa-1x fa fa-paperclip px-4 py-4 m-auto text-dark"></i>
                                </h1>
                                <div class="media-body my-auto">
                                    <h2 class="my-0 text-secondary">Laporan Transaksi</h2>
                                    <hr class="mt-0 mb-2">
                                    {{-- <h5 class="text-dark mb-0">
                                         Pasien
                                    </h5> --}}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-xl-6 col-md-6 col-12 mb-4">
                    <a href="{{ route('dashboard.roadmap')  }}" class="dashboard card shadow" style="border-radius: 1rem;">
                        <div class="card-header bg-purple-old-fade py-2" style="
                        background-color: red;
                        border-radius: 1rem 1rem 0rem 0rem;">
                            <h5 class="text-white mb-0">
                                Peta Road Map
                            </h5>
                        </div>
                        <div class="card-body">
                            {{-- Amount --}}
                            <div class="media">
                                <h1 class="mr-2 d-flex">
                                    <i class="fa fa-1x fa-map-marker px-4 py-4 m-auto text-dark"></i>
                                </h1>
                                <div class="media-body my-auto">
                                    <h2 class="my-0 text-secondary">Peta Roadmap Pelanggan</h2>
                                    <hr class="mt-0 mb-2">
                                    {{-- <h5 class="text-dark mb-0">
                                         Pasien
                                    </h5> --}}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-xl-6 col-md-6 col-12 mb-4">
                    <a href="{{ route('dashboard.pengaturan')  }}" class="dashboard card shadow" style="border-radius: 1rem;">
                        <div class="card-header bg-purple-old-fade py-2" style="
                        background-color: red;
                        border-radius: 1rem 1rem 0rem 0rem;">
                            <h5 class="text-white mb-0">
                                Pengaturan
                            </h5>
                        </div>
                        <div class="card-body">
                            {{-- Amount --}}
                            <div class="media">
                                <h1 class="mr-2 d-flex">
                                    <i class="fa fa-1x fa-cog px-4 py-4 m-auto text-dark"></i>
                                </h1>
                                <div class="media-body my-auto">
                                    <h2 class="my-0 text-secondary">Pengaturan Dashboard</h2>
                                    <hr class="mt-0 mb-2">
                                    {{-- <h5 class="text-dark mb-0">
                                         Pasien
                                    </h5> --}}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-xl-6 col-md-6 col-12 mb-4">
                    <a href="{{ route('dashboard.manajemen')  }}" class="dashboard card shadow" style="border-radius: 1rem;">
                        <div class="card-header bg-purple-old-fade py-2" style="
                        background-color: red;
                        border-radius: 1rem 1rem 0rem 0rem;">
                            <h5 class="text-white mb-0">
                               Manajemen
                            </h5>
                        </div>
                        <div class="card-body">
                            {{-- Amount --}}
                            <div class="media">
                                <h1 class="mr-2 d-flex">
                                    <i class="fa fa-1x fa-briefcase px-4 py-4 m-auto text-dark"></i>
                                </h1>
                                <div class="media-body my-auto">
                                    <h2 class="my-0 text-secondary">Manajemen</h2>
                                    <hr class="mt-0 mb-2">
                                    {{-- <h5 class="text-dark mb-0">
                                         Pasien
                                    </h5> --}}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                
        </div>
    </div>
</div>
@endsection